title: "NiMARE: Neuroimaging Meta-Analysis Research Environment"
logo: images/nimare_overview.png
execute:
  execute_notebooks: "off"
bibtex_bibfiles:
  - references.bib
sphinx:
  config:
    bibtex_reference_style: author_year
