title: "NiMARE: Neuroimaging Meta-Analysis Research Environment"
logo: figures/nimare_overview.png
execute:
  execute_notebooks: "off"
exclude_patterns: ["README.md", "misc-notebooks/*"]
bibtex_bibfiles:
  - _bibliography/references.bib
sphinx:
  config:
    bibtex_reference_style: author_year
    intersphinx_mapping:
      nimare: https://nimare.readthedocs.io/en/stable/objects.inv
